[project]
name = "ispunct"
version = "1.0.2"
description = "Small Python library to check if a character is a punctuation character"
authors = [
    { name = "Jake W. Ireland", email = "jakewilliami@icloud.com" },
]
readme = "README.md"
requires-python = ">=3.9, <4.0.0"
dependencies = []

[dependency-groups]
dev = [
    "pip-audit>=2.9.0",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.4",
]

[tool.pytest.ini_options]
pythonpath = "src"

[tool.ruff]
# https://peps.python.org/pep-0008/#maximum-line-length
line-length = 80

[tool.ruff.lint]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
]
ignore = [
    # "B008",  # docs.astral.sh/ruff/rules/function-call-in-default-argument/
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports
